# Generated by Django 5.1.6 on 2025-03-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0003_farmer_consent_form_farmer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer_consent',
            field=models.BooleanField(default=True),
        ),
    ]
