# Generated by Django 5.1.6 on 2025-03-18 04:28

import data_collection.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0004_alter_farmer_farmer_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='block_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='country_id',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='FarmerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path)),
                ('photo_of_english_epic', models.ImageField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path)),
                ('photo_of_regional_language_epic', models.ImageField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path)),
                ('id_proof_front', models.ImageField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path)),
                ('id_proof_back', models.ImageField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path)),
                ('land_ownership', models.FileField(upload_to=data_collection.models.farmer_media_path)),
                ('picture_of_tree', models.ImageField(upload_to=data_collection.models.farmer_media_path)),
                ('digital_signature', models.ImageField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='data_collection.farmer')),
            ],
        ),
    ]
