# Generated by Django 5.1.6 on 2025-03-21 05:30

import data_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0005_alter_farmer_block_id_alter_farmer_country_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmermedia',
            name='id_proof_back',
        ),
        migrations.RemoveField(
            model_name='farmermedia',
            name='id_proof_front',
        ),
        migrations.AddField(
            model_name='farmermedia',
            name='id_number',
            field=models.CharField(blank=True, help_text='The ID number corresponding to the selected ID type.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmermedia',
            name='id_proof',
            field=models.FileField(blank=True, help_text='PDF file containing both front and back sides of the ID card.', null=True, upload_to=data_collection.models.farmer_media_path),
        ),
        migrations.AddField(
            model_name='farmermedia',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('ration_card', 'Ration Card'), ('pan_card', 'PAN Card')], help_text='Type of ID proof provided by the farmer.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmermedia',
            name='land_ownership',
            field=models.FileField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path),
        ),
        migrations.AlterField(
            model_name='farmermedia',
            name='photo_of_english_epic',
            field=models.FileField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path),
        ),
        migrations.AlterField(
            model_name='farmermedia',
            name='photo_of_regional_language_epic',
            field=models.FileField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path),
        ),
        migrations.AlterField(
            model_name='farmermedia',
            name='picture_of_tree',
            field=models.ImageField(blank=True, null=True, upload_to=data_collection.models.farmer_media_path),
        ),
    ]
