# Generated by Django 5.1.6 on 2025-03-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0006_remove_farmermedia_id_proof_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='consent_form',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='kyari_type',
            field=models.CharField(default='Retrospective', max_length=50),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='plantation_model',
            field=models.CharField(default='BLOCK', max_length=50),
        ),
    ]
