# Generated by Django 5.1.6 on 2025-03-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0007_remove_farmer_aadhar_remove_farmer_consent_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
