# Generated by Django 5.1.6 on 2025-03-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0008_alter_farmer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
