# Generated by Django 5.1.6 on 2025-03-21 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0009_alter_farmer_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='plantation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantation',
            name='kyari_type',
            field=models.CharField(default='RETROSPECTIVE', max_length=50),
        ),
    ]
