# Generated by Django 5.1.6 on 2025-03-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0010_specie_plantation_date_alter_plantation_kyari_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='vaarha_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='vaarha_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmermedia',
            name='vaarha_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantation',
            name='vaarha_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='vaarha_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GeotaggedSapling',
        ),
    ]
