# Generated by Django 5.1.6 on 2025-03-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0011_farm_vaarha_id_farmer_vaarha_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmermedia',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmermedia',
            name='vaarha_doc_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmermedia',
            name='vaarha_document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmermedia',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhar', 'Aadhar Card'), ('driving_licence', 'Driving License'), ('voter_id', 'Voter ID'), ('pan_card', 'PAN Card')], help_text='Type of ID proof provided by the farmer.', max_length=50, null=True),
        ),
    ]
