# Generated by Django 5.1.6 on 2025-04-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0013_remove_farmermedia_picture_of_tree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='landlord_declaration',
            field=models.FileField(blank=True, null=True, upload_to='farm_landlord_declarations/'),
        ),
    ]
