# Generated by Django 5.1.6 on 2025-04-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0014_farm_landlord_declaration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmermedia',
            name='centre_bottom',
        ),
        migrations.RemoveField(
            model_name='farmermedia',
            name='centre_left',
        ),
        migrations.RemoveField(
            model_name='farmermedia',
            name='centre_right',
        ),
        migrations.RemoveField(
            model_name='farmermedia',
            name='centre_top',
        ),
        migrations.AddField(
            model_name='specie',
            name='centre_bottom',
            field=models.ImageField(blank=True, null=True, upload_to='tree_pictures/'),
        ),
        migrations.AddField(
            model_name='specie',
            name='centre_left',
            field=models.ImageField(blank=True, null=True, upload_to='tree_pictures/'),
        ),
        migrations.AddField(
            model_name='specie',
            name='centre_right',
            field=models.ImageField(blank=True, null=True, upload_to='tree_pictures/'),
        ),
        migrations.AddField(
            model_name='specie',
            name='centre_top',
            field=models.ImageField(blank=True, null=True, upload_to='tree_pictures/'),
        ),
    ]
