# Generated by Django 5.1.6 on 2025-04-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0015_remove_farmermedia_centre_bottom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantation',
            name='number_of_saplings',
        ),
    ]
