# Generated by Django 5.1.6 on 2025-04-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0016_remove_plantation_number_of_saplings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmermedia',
            name='land_ownership',
        ),
        migrations.AddField(
            model_name='farm',
            name='land_ownership',
            field=models.FileField(blank=True, null=True, upload_to='land_doc/'),
        ),
    ]
