# Generated by Django 5.1.6 on 2025-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0017_remove_farmermedia_land_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='land_ownership',
            field=models.FileField(blank=True, null=True, upload_to='land_documents/'),
        ),
    ]
