# Generated by Django 5.1.6 on 2025-04-03 07:59

import data_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0018_alter_farm_land_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='centre_bottom',
            field=models.ImageField(blank=True, null=True, upload_to=data_collection.models.specie_image_upload),
        ),
        migrations.AlterField(
            model_name='specie',
            name='centre_left',
            field=models.ImageField(blank=True, null=True, upload_to=data_collection.models.specie_image_upload),
        ),
        migrations.AlterField(
            model_name='specie',
            name='centre_right',
            field=models.ImageField(blank=True, null=True, upload_to=data_collection.models.specie_image_upload),
        ),
        migrations.AlterField(
            model_name='specie',
            name='centre_top',
            field=models.ImageField(blank=True, null=True, upload_to=data_collection.models.specie_image_upload),
        ),
    ]
