# Generated by Django 5.1.6 on 2025-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0019_alter_specie_centre_bottom_alter_specie_centre_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantation',
            old_name='year',
            new_name='plantation_year',
        ),
        migrations.AlterField(
            model_name='farm',
            name='boundary_method',
            field=models.CharField(choices=[('Drawing', 'Drawing'), ('Tapping', 'Tapping')], default='Drawing', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
